// <auto-generated />
using System;
using System.Collections.Generic;
using Balance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balance.Data.Sqlite.Migrations
{
    [DbContext(typeof(BalanceDbContext))]
    [Migration("20260620145548_AddAccountHorizon")]
    partial class AddAccountHorizon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Balance.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_Code");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("ParentAccountId")
                        .HasDatabaseName("IX_Accounts_ParentAccountId");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            AccountType = "Equity",
                            Code = "3900",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "EUR",
                            Horizon = "ShortTerm",
                            IsLiquid = true,
                            IsPostable = true,
                            Name = "Opening Balances",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ApiTokens_UserId");

                    b.ToTable("ApiTokens", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.BalanceUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberFormat")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bic")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImporterKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Current");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_BankAccounts_AccountId")
                        .HasFilter("\"AccountId\" IS NOT NULL");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("IX_BankAccounts_CounterpartyId");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("Iban")
                        .IsUnique()
                        .HasDatabaseName("IX_BankAccounts_Iban")
                        .HasFilter("\"Iban\" IS NOT NULL");

                    b.ToTable("BankAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankAccounts_CardOwnedOnly", "\"Type\" <> 'Card' OR \"AccountId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_BankAccounts_CurrencyRequiredWhenOwned", "\"AccountId\" IS NULL OR \"CurrencyCode\" IS NOT NULL");

                            t.HasCheckConstraint("CK_BankAccounts_IdentifierByType", "(\"Type\" = 'Current' AND \"Iban\" IS NOT NULL) OR (\"Type\" = 'Savings' AND (\"Iban\" IS NOT NULL OR \"AccountNumber\" IS NOT NULL)) OR (\"Type\" = 'Card' AND \"CardIdentifier\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_BankAccounts_OwnershipXor", "(\"AccountId\" IS NULL) <> (\"CounterpartyId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterpartyAccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterpartyName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DismissedReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ForeignAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForeignCurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImporterKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MandateId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("SepaCreditorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "Balance.Data.Entities.BankTransaction.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Amount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrencyCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("IX_BankTransactions_BankAccountId");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("IX_BankTransactions_BookingDate");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("IX_BankTransactions_JournalEntryId");

                    b.HasIndex("BankAccountId", "RowHash")
                        .IsUnique()
                        .HasDatabaseName("UX_BankTransactions_BankAccountId_RowHash");

                    b.ToTable("BankTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankTransactions_Amount_NonZero", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_BankTransactions_Dismissed_Pair", "(\"DismissedAt\" IS NULL AND \"DismissedReason\" IS NULL) OR (\"DismissedAt\" IS NOT NULL AND \"DismissedReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransactionMetadataKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_BankTransactionMetadataKeys_Name");

                    b.ToTable("BankTransactionMetadataKeys", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransactionMetadataValue", b =>
                {
                    b.Property<Guid>("BankTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("BankTransactionId", "KeyId");

                    b.HasIndex("KeyId")
                        .HasDatabaseName("IX_BankTransactionMetadataValues_KeyId");

                    b.ToTable("BankTransactionMetadataValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankTransactionMetadataValues_Value_Exactly_One", "(\"StringValue\" IS NULL) <> (\"IntegerValue\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Counterparties_Name");

                    b.ToTable("Counterparties", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinorUnitScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "EUR",
                            MinorUnitScale = 2,
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("IX_JournalEntries_CounterpartyId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_JournalEntries_Date");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CounterAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MandateId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SepaCreditorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_JournalEntryTemplates_AccountId");

                    b.HasIndex("CounterAccountId");

                    b.HasIndex("CounterpartyId");

                    b.ToTable("JournalEntryTemplates", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LoanPartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_JournalLines_AccountId");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("IX_JournalLines_JournalEntryId");

                    b.HasIndex("LoanPartId")
                        .HasDatabaseName("IX_JournalLines_LoanPartId");

                    b.ToTable("JournalLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_JournalLines_Amount_NonZero", "\"Amount\" <> 0");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConstructionDepositAccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConstructionDepositAnnualRatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConstructionDepositInterestIncomeAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterestExpenseAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LenderCounterpartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionDepositAccountId");

                    b.HasIndex("ConstructionDepositInterestIncomeAccountId");

                    b.HasIndex("InterestExpenseAccountId")
                        .HasDatabaseName("IX_Loans_InterestExpenseAccountId");

                    b.HasIndex("LenderCounterpartyId")
                        .HasDatabaseName("IX_Loans_LenderCounterpartyId");

                    b.HasIndex("ParentAccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_Loans_ParentAccountId");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.LoanPart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepaymentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_LoanParts_AccountId");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("IX_LoanParts_LoanId");

                    b.ToTable("LoanParts", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.LoanPartRatePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FixedUntil")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoanPartId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoanPartId", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("IX_LoanPartRatePeriods_LoanPartId_EffectiveDate");

                    b.ToTable("LoanPartRatePeriods", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<Balance.Data.Entities.Ids.UserId>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<Balance.Data.Entities.Ids.UserId>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<Balance.Data.Entities.Ids.UserId>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.Account", b =>
                {
                    b.HasOne("Balance.Data.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Balance.Data.Entities.ApiToken", b =>
                {
                    b.HasOne("Balance.Data.Entities.BalanceUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.BankAccount", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransaction", b =>
                {
                    b.HasOne("Balance.Data.Entities.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransactionMetadataValue", b =>
                {
                    b.HasOne("Balance.Data.Entities.BankTransaction", null)
                        .WithMany("Metadata")
                        .HasForeignKey("BankTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.BankTransactionMetadataKey", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Key");
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntry", b =>
                {
                    b.HasOne("Balance.Data.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntryTemplate", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("CounterAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalLine", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.LoanPart", null)
                        .WithMany()
                        .HasForeignKey("LoanPartId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Balance.Data.Entities.Loan", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("ConstructionDepositAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("ConstructionDepositInterestIncomeAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("InterestExpenseAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("LenderCounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.LoanPart", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.Loan", null)
                        .WithMany("Parts")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.LoanPartRatePeriod", b =>
                {
                    b.HasOne("Balance.Data.Entities.LoanPart", null)
                        .WithMany("RatePeriods")
                        .HasForeignKey("LoanPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<Balance.Data.Entities.Ids.UserId>", b =>
                {
                    b.HasOne("Balance.Data.Entities.BalanceUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<Balance.Data.Entities.Ids.UserId>", b =>
                {
                    b.HasOne("Balance.Data.Entities.BalanceUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<Balance.Data.Entities.Ids.UserId>", b =>
                {
                    b.HasOne("Balance.Data.Entities.BalanceUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransaction", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Balance.Data.Entities.Loan", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Balance.Data.Entities.LoanPart", b =>
                {
                    b.Navigation("RatePeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
