// <auto-generated />
using System;
using Balance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balance.Data.Sqlite.Migrations
{
    [DbContext(typeof(BalanceDbContext))]
    [Migration("20260516190352_Counterparties")]
    partial class Counterparties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Balance.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_Name");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            AccountType = "Equity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "EUR",
                            Name = "Opening Balances",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Counterparties_Name");

                    b.ToTable("Counterparties", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinorUnitScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "EUR",
                            MinorUnitScale = 2,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "USD",
                            MinorUnitScale = 2,
                            Name = "United States Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "GBP",
                            MinorUnitScale = 2,
                            Name = "Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Code = "JPY",
                            MinorUnitScale = 0,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "CHF",
                            MinorUnitScale = 2,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Code = "BTC",
                            MinorUnitScale = 8,
                            Name = "Bitcoin",
                            Symbol = "₿"
                        },
                        new
                        {
                            Code = "ETH",
                            MinorUnitScale = 18,
                            Name = "Ether",
                            Symbol = "Ξ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Balance.Data.Entities.Account", b =>
                {
                    b.HasOne("Balance.Data.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
