// <auto-generated />
using Balance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balance.Data.Sqlite.Migrations
{
    [DbContext(typeof(BalanceDbContext))]
    partial class BalanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Balance.Data.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinorUnitScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "EUR",
                            MinorUnitScale = 2,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "USD",
                            MinorUnitScale = 2,
                            Name = "United States Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "GBP",
                            MinorUnitScale = 2,
                            Name = "Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Code = "JPY",
                            MinorUnitScale = 0,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "CHF",
                            MinorUnitScale = 2,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Code = "BTC",
                            MinorUnitScale = 8,
                            Name = "Bitcoin",
                            Symbol = "₿"
                        },
                        new
                        {
                            Code = "ETH",
                            MinorUnitScale = 18,
                            Name = "Ether",
                            Symbol = "Ξ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
