import { asJournalEntryId, type JournalEntrySummary } from '../lib/domain';
import {
    ACCOUNT_BILLS,
    ACCOUNT_CHECKING,
    ACCOUNT_CREDIT,
    ACCOUNT_DINING,
    ACCOUNT_GROCERIES,
    ACCOUNT_RENT,
    ACCOUNT_SALARY,
    ACCOUNT_SAVINGS,
    ACCOUNT_TRANSPORT,
} from './accounts';

/*
 * Seeded JournalEntries. Each row is one entry shown from the focal
 * Asset/Liability account's perspective — amountMinor is the net effect on
 * that account (negative = money out). categoryAccount* describes the
 * offsetting Expense/Income account that the badge / dot represents.
 */
export const ENTRIES: JournalEntrySummary[] = [
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f01'),
        date: '2026-05-16',
        counterpartyName: 'Albert Heijn',
        description: 'Weekly groceries',
        amountMinor: -42_50,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CHECKING,
        categoryAccountId: ACCOUNT_GROCERIES,
        categoryAccountName: 'Groceries',
        accentColor: 'var(--color-cat-food)',
        iconName: 'shopping-cart',
    },
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f02'),
        date: '2026-05-15',
        counterpartyName: 'Acme Co.',
        description: 'May salary',
        amountMinor: 3_250_00,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CHECKING,
        categoryAccountId: ACCOUNT_SALARY,
        categoryAccountName: 'Salary',
        accentColor: 'var(--color-cat-entertain)',
        iconName: 'banknote',
    },
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f03'),
        date: '2026-05-14',
        counterpartyName: 'Landlord',
        description: 'May rent',
        amountMinor: -1_200_00,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CHECKING,
        categoryAccountId: ACCOUNT_RENT,
        categoryAccountName: 'Rent',
        accentColor: 'var(--color-cat-housing)',
        iconName: 'home',
    },
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f04'),
        date: '2026-05-13',
        counterpartyName: 'NS',
        description: 'OV chip top-up',
        amountMinor: -25_00,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CHECKING,
        categoryAccountId: ACCOUNT_TRANSPORT,
        categoryAccountName: 'Transport',
        accentColor: 'var(--color-cat-transport)',
        iconName: 'train',
    },
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f05'),
        date: '2026-05-12',
        counterpartyName: 'Blue Bottle Coffee',
        description: null,
        amountMinor: -4_75,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CREDIT,
        categoryAccountId: ACCOUNT_DINING,
        categoryAccountName: 'Dining',
        accentColor: 'var(--color-cat-food)',
        iconName: 'coffee',
    },
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f06'),
        date: '2026-05-11',
        counterpartyName: null,
        description: 'Transfer to savings',
        amountMinor: -300_00,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CHECKING,
        categoryAccountId: ACCOUNT_SAVINGS,
        categoryAccountName: 'Savings',
        accentColor: 'var(--color-cat-savings)',
        iconName: 'arrow-left-right',
    },
    {
        id: asJournalEntryId('019709a8-4f60-7c11-b6a1-3c2c1a3d9f07'),
        date: '2026-05-10',
        counterpartyName: 'Eneco',
        description: 'May electricity',
        amountMinor: -78_40,
        currencyCode: 'EUR',
        accountId: ACCOUNT_CHECKING,
        categoryAccountId: ACCOUNT_BILLS,
        categoryAccountName: 'Bills',
        accentColor: 'var(--color-cat-bills)',
        iconName: 'zap',
    },
];
