import {
    AlertCircle,
    ArrowLeftRight,
    ArrowRight,
    Baby,
    Banknote,
    Bike,
    Bitcoin,
    Briefcase,
    Building2,
    Bell,
    Binoculars,
    BookOpen,
    CalendarDays,
    Car,
    CheckCircle2,
    ChevronRight,
    CircleHelp,
    Cloud,
    Coffee,
    CreditCard,
    Download,
    Dumbbell,
    FolderTree,
    Fuel,
    Gamepad2,
    Gift,
    GraduationCap,
    Heart,
    Home,
    Inbox,
    Info,
    Landmark,
    LayoutDashboard,
    Leaf,
    LineChart,
    Link as LinkIcon,
    LogOut,
    Unlink,
    User,
    Menu,
    MonitorSmartphone,
    Moon,
    MoreVertical,
    Music,
    Palette,
    PawPrint,
    Pencil,
    Percent,
    PiggyBank,
    Plane,
    Plus,
    Repeat,
    Search,
    Settings,
    Shirt,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Stethoscope,
    Sun,
    Train,
    Trash2,
    TrendingDown,
    TrendingUp,
    Tv,
    Umbrella,
    Utensils,
    Wallet,
    X,
    Zap,
    type LucideIcon,
    type LucideProps,
    Shield,
    Wrench,
    CircleQuestionMark,
    ShoppingBasket,
    Store,
    Motorbike,
    CalendarSync,
    Amphora,
    RollerCoaster,
    FerrisWheel,
    Palmtree,
    Sparkles,
    EvCharger,
    Road,
    Sofa,
    ChevronDown,
} from 'lucide-react';

/*
 * Icon registry. Demo data references icons by kebab-case names (so a
 * future API can carry them as strings); the component maps each name to a
 * tree-shaken lucide-react import. Add new icons here as screens grow.
 */
const REGISTRY: Record<string, LucideIcon> = {
    amphora: Amphora,
    'alert-circle': AlertCircle,
    'arrow-left-right': ArrowLeftRight,
    'arrow-right': ArrowRight,
    baby: Baby,
    bank: Building2,
    banknote: Banknote,
    bell: Bell,
    bike: Bike,
    binoculars: Binoculars,
    bitcoin: Bitcoin,
    'book-open': BookOpen,
    briefcase: Briefcase,
    calendar: CalendarDays,
    'calendar-sync': CalendarSync,
    car: Car,
    'check-circle': CheckCircle2,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'circle-question-mark': CircleQuestionMark,
    cloud: Cloud,
    coffee: Coffee,
    'credit-card': CreditCard,
    download: Download,
    dumbbell: Dumbbell,
    'ev-charger': EvCharger,
    'ferris-wheel': FerrisWheel,
    'folder-tree': FolderTree,
    fuel: Fuel,
    gamepad: Gamepad2,
    gift: Gift,
    'graduation-cap': GraduationCap,
    heart: Heart,
    home: Home,
    inbox: Inbox,
    info: Info,
    landmark: Landmark,
    'layout-dashboard': LayoutDashboard,
    leaf: Leaf,
    'line-chart': LineChart,
    link: LinkIcon,
    'log-out': LogOut,
    unlink: Unlink,
    user: User,
    menu: Menu,
    'monitor-smartphone': MonitorSmartphone,
    moon: Moon,
    'more-vertical': MoreVertical,
    motorbike: Motorbike,
    music: Music,
    palette: Palette,
    palmtree: Palmtree,
    'paw-print': PawPrint,
    pencil: Pencil,
    percent: Percent,
    'piggy-bank': PiggyBank,
    plane: Plane,
    plus: Plus,
    repeat: Repeat,
    road: Road,
    'roller-coaster': RollerCoaster,
    search: Search,
    settings: Settings,
    shirt: Shirt,
    shield: Shield,
    'shopping-bag': ShoppingBag,
    'shopping-basket': ShoppingBasket,
    'shopping-cart': ShoppingCart,
    smartphone: Smartphone,
    sofa: Sofa,
    sparkles: Sparkles,
    stethoscope: Stethoscope,
    store: Store,
    sun: Sun,
    train: Train,
    trash: Trash2,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    tv: Tv,
    umbrella: Umbrella,
    utensils: Utensils,
    wallet: Wallet,
    wrench: Wrench,
    x: X,
    zap: Zap,
};

export type IconProps = LucideProps & { name: string };

export function Icon({ name, ...rest }: IconProps) {
    const Component = REGISTRY[name] ?? CircleHelp;
    return <Component {...rest} />;
}
