import {
    AlertCircle,
    ArrowLeftRight,
    ArrowRight,
    Baby,
    Banknote,
    Bike,
    Bitcoin,
    Briefcase,
    Building2,
    Bell,
    BookOpen,
    Car,
    CheckCircle2,
    ChevronRight,
    CircleHelp,
    Cloud,
    Coffee,
    CreditCard,
    Download,
    Dumbbell,
    FolderTree,
    Fuel,
    Gamepad2,
    Gift,
    GraduationCap,
    Heart,
    Home,
    Inbox,
    Info,
    Landmark,
    LayoutDashboard,
    Leaf,
    LineChart,
    Link as LinkIcon,
    LogOut,
    Unlink,
    User,
    Menu,
    MoreVertical,
    Music,
    Palette,
    PawPrint,
    Pencil,
    PiggyBank,
    Plane,
    Plus,
    Repeat,
    Search,
    Settings,
    Shirt,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Stethoscope,
    Train,
    Trash2,
    TrendingDown,
    TrendingUp,
    Tv,
    Umbrella,
    Utensils,
    Wallet,
    X,
    Zap,
    type LucideIcon,
    type LucideProps,
} from 'lucide-react';

/*
 * Icon registry. Demo data references icons by kebab-case names (so a
 * future API can carry them as strings); the component maps each name to a
 * tree-shaken lucide-react import. Add new icons here as screens grow.
 */
const REGISTRY: Record<string, LucideIcon> = {
    'alert-circle': AlertCircle,
    'arrow-left-right': ArrowLeftRight,
    'arrow-right': ArrowRight,
    baby: Baby,
    bank: Building2,
    banknote: Banknote,
    bell: Bell,
    bike: Bike,
    bitcoin: Bitcoin,
    'book-open': BookOpen,
    briefcase: Briefcase,
    car: Car,
    'check-circle': CheckCircle2,
    'chevron-right': ChevronRight,
    cloud: Cloud,
    coffee: Coffee,
    'credit-card': CreditCard,
    download: Download,
    dumbbell: Dumbbell,
    'folder-tree': FolderTree,
    fuel: Fuel,
    gamepad: Gamepad2,
    gift: Gift,
    'graduation-cap': GraduationCap,
    heart: Heart,
    home: Home,
    inbox: Inbox,
    info: Info,
    landmark: Landmark,
    'layout-dashboard': LayoutDashboard,
    leaf: Leaf,
    'line-chart': LineChart,
    link: LinkIcon,
    'log-out': LogOut,
    unlink: Unlink,
    user: User,
    menu: Menu,
    'more-vertical': MoreVertical,
    music: Music,
    palette: Palette,
    'paw-print': PawPrint,
    pencil: Pencil,
    'piggy-bank': PiggyBank,
    plane: Plane,
    plus: Plus,
    repeat: Repeat,
    search: Search,
    settings: Settings,
    shirt: Shirt,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    smartphone: Smartphone,
    stethoscope: Stethoscope,
    train: Train,
    trash: Trash2,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    tv: Tv,
    umbrella: Umbrella,
    utensils: Utensils,
    wallet: Wallet,
    x: X,
    zap: Zap,
};

export type IconProps = LucideProps & { name: string };

export function Icon({ name, ...rest }: IconProps) {
    const Component = REGISTRY[name] ?? CircleHelp;
    return <Component {...rest} />;
}
