// <auto-generated />
using System;
using System.Collections.Generic;
using Balance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balance.Data.PostgreSql.Migrations
{
    [DbContext(typeof(BalanceDbContext))]
    [Migration("20260526131959_BankTransactionMetadataTables")]
    partial class BankTransactionMetadataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balance.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_Name");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            AccountType = "Equity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "EUR",
                            Name = "Opening Balances",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BankName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Bic")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_BankAccounts_AccountId")
                        .HasFilter("\"AccountId\" IS NOT NULL");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("IX_BankAccounts_CounterpartyId");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("Iban")
                        .IsUnique()
                        .HasDatabaseName("IX_BankAccounts_Iban")
                        .HasFilter("\"Iban\" IS NOT NULL");

                    b.ToTable("BankAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankAccounts_CurrencyRequiredWhenOwned", "\"AccountId\" IS NULL OR \"CurrencyCode\" IS NOT NULL");

                            t.HasCheckConstraint("CK_BankAccounts_IbanOrAccountNumber", "\"Iban\" IS NOT NULL OR \"AccountNumber\" IS NOT NULL");

                            t.HasCheckConstraint("CK_BankAccounts_OwnershipXor", "(\"AccountId\" IS NULL) <> (\"CounterpartyId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("CounterpartyAccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CounterpartyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DismissedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<long?>("ForeignAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("ForeignCurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ImporterKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MandateId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RawSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("SepaCreditorId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "Balance.Data.Entities.BankTransaction.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("CurrencyCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("IX_BankTransactions_BankAccountId");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("IX_BankTransactions_BookingDate");

                    b.HasIndex("BankAccountId", "RowHash")
                        .IsUnique()
                        .HasDatabaseName("UX_BankTransactions_BankAccountId_RowHash");

                    b.ToTable("BankTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankTransactions_Amount_NonZero", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_BankTransactions_Dismissed_Pair", "(\"DismissedAt\" IS NULL AND \"DismissedReason\" IS NULL) OR (\"DismissedAt\" IS NOT NULL AND \"DismissedReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransactionMetadataKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_BankTransactionMetadataKeys_Name");

                    b.ToTable("BankTransactionMetadataKeys", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransactionMetadataValue", b =>
                {
                    b.Property<Guid>("BankTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uuid");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("bigint");

                    b.Property<string>("StringValue")
                        .HasColumnType("text");

                    b.HasKey("BankTransactionId", "KeyId");

                    b.HasIndex("KeyId")
                        .HasDatabaseName("IX_BankTransactionMetadataValues_KeyId");

                    b.ToTable("BankTransactionMetadataValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankTransactionMetadataValues_Value_Exactly_One", "(\"StringValue\" IS NULL) <> (\"IntegerValue\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Counterparties_Name");

                    b.ToTable("Counterparties", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("MinorUnitScale")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Code");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "EUR",
                            MinorUnitScale = 2,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "USD",
                            MinorUnitScale = 2,
                            Name = "United States Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "GBP",
                            MinorUnitScale = 2,
                            Name = "Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Code = "JPY",
                            MinorUnitScale = 0,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "CHF",
                            MinorUnitScale = 2,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Code = "BTC",
                            MinorUnitScale = 8,
                            Name = "Bitcoin",
                            Symbol = "₿"
                        },
                        new
                        {
                            Code = "ETH",
                            MinorUnitScale = 18,
                            Name = "Ether",
                            Symbol = "Ξ"
                        });
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BankTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_JournalEntries_BankTransactionId")
                        .HasFilter("\"BankTransactionId\" IS NOT NULL");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("IX_JournalEntries_CounterpartyId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_JournalEntries_Date");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_JournalLines_AccountId");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("IX_JournalLines_JournalEntryId");

                    b.ToTable("JournalLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_JournalLines_Amount_NonZero", "\"Amount\" <> 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Balance.Data.Entities.Account", b =>
                {
                    b.HasOne("Balance.Data.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.BankAccount", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Balance.Data.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransaction", b =>
                {
                    b.HasOne("Balance.Data.Entities.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransactionMetadataValue", b =>
                {
                    b.HasOne("Balance.Data.Entities.BankTransaction", null)
                        .WithMany("Metadata")
                        .HasForeignKey("BankTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.BankTransactionMetadataKey", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Key");
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntry", b =>
                {
                    b.HasOne("Balance.Data.Entities.BankTransaction", null)
                        .WithMany()
                        .HasForeignKey("BankTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Balance.Data.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalLine", b =>
                {
                    b.HasOne("Balance.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Balance.Data.Entities.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Balance.Data.Entities.BankTransaction", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Balance.Data.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
