/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PiggyBanksRouteImport } from './routes/piggy-banks'
import { Route as OutlookRouteImport } from './routes/outlook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as CounterpartiesRouteImport } from './routes/counterparties'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as BankTransactionsRouteImport } from './routes/bank-transactions'
import { Route as BankImportsRouteImport } from './routes/bank-imports'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as CounterpartiesIndexRouteImport } from './routes/counterparties.index'
import { Route as BankTransactionsIndexRouteImport } from './routes/bank-transactions.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsTokensRouteImport } from './routes/settings.tokens'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsCurrenciesRouteImport } from './routes/settings.currencies'
import { Route as SettingsBankAccountsRouteImport } from './routes/settings.bank-accounts'
import { Route as LoansIdRouteImport } from './routes/loans.$id'
import { Route as JournalNewRouteImport } from './routes/journal.new'
import { Route as JournalIdRouteImport } from './routes/journal.$id'
import { Route as CounterpartiesIdRouteImport } from './routes/counterparties.$id'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as SettingsBankAccountsIndexRouteImport } from './routes/settings.bank-accounts.index'
import { Route as SettingsBankAccountsIdRouteImport } from './routes/settings.bank-accounts.$id'
import { Route as BankTransactionsIdCategorizeRouteImport } from './routes/bank-transactions.$id.categorize'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PiggyBanksRoute = PiggyBanksRouteImport.update({
  id: '/piggy-banks',
  path: '/piggy-banks',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookRoute = OutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterpartiesRoute = CounterpartiesRouteImport.update({
  id: '/counterparties',
  path: '/counterparties',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const BankTransactionsRoute = BankTransactionsRouteImport.update({
  id: '/bank-transactions',
  path: '/bank-transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const BankImportsRoute = BankImportsRouteImport.update({
  id: '/bank-imports',
  path: '/bank-imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoansRoute,
} as any)
const CounterpartiesIndexRoute = CounterpartiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CounterpartiesRoute,
} as any)
const BankTransactionsIndexRoute = BankTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BankTransactionsRoute,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCurrenciesRoute = SettingsCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBankAccountsRoute = SettingsBankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => SettingsRoute,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LoansRoute,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JournalRoute,
} as any)
const JournalIdRoute = JournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JournalRoute,
} as any)
const CounterpartiesIdRoute = CounterpartiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CounterpartiesRoute,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const SettingsBankAccountsIndexRoute =
  SettingsBankAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsBankAccountsRoute,
  } as any)
const SettingsBankAccountsIdRoute = SettingsBankAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsBankAccountsRoute,
} as any)
const BankTransactionsIdCategorizeRoute =
  BankTransactionsIdCategorizeRouteImport.update({
    id: '/$id/categorize',
    path: '/$id/categorize',
    getParentRoute: () => BankTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/bank-imports': typeof BankImportsRoute
  '/bank-transactions': typeof BankTransactionsRouteWithChildren
  '/budgets': typeof BudgetsRoute
  '/counterparties': typeof CounterpartiesRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/outlook': typeof OutlookRoute
  '/piggy-banks': typeof PiggyBanksRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/counterparties/$id': typeof CounterpartiesIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
  '/loans/$id': typeof LoansIdRoute
  '/settings/bank-accounts': typeof SettingsBankAccountsRouteWithChildren
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts/': typeof AccountsIndexRoute
  '/bank-transactions/': typeof BankTransactionsIndexRoute
  '/counterparties/': typeof CounterpartiesIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bank-transactions/$id/categorize': typeof BankTransactionsIdCategorizeRoute
  '/settings/bank-accounts/$id': typeof SettingsBankAccountsIdRoute
  '/settings/bank-accounts/': typeof SettingsBankAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bank-imports': typeof BankImportsRoute
  '/budgets': typeof BudgetsRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/outlook': typeof OutlookRoute
  '/piggy-banks': typeof PiggyBanksRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/counterparties/$id': typeof CounterpartiesIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
  '/loans/$id': typeof LoansIdRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts': typeof AccountsIndexRoute
  '/bank-transactions': typeof BankTransactionsIndexRoute
  '/counterparties': typeof CounterpartiesIndexRoute
  '/loans': typeof LoansIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/bank-transactions/$id/categorize': typeof BankTransactionsIdCategorizeRoute
  '/settings/bank-accounts/$id': typeof SettingsBankAccountsIdRoute
  '/settings/bank-accounts': typeof SettingsBankAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/bank-imports': typeof BankImportsRoute
  '/bank-transactions': typeof BankTransactionsRouteWithChildren
  '/budgets': typeof BudgetsRoute
  '/counterparties': typeof CounterpartiesRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/outlook': typeof OutlookRoute
  '/piggy-banks': typeof PiggyBanksRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/counterparties/$id': typeof CounterpartiesIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
  '/loans/$id': typeof LoansIdRoute
  '/settings/bank-accounts': typeof SettingsBankAccountsRouteWithChildren
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts/': typeof AccountsIndexRoute
  '/bank-transactions/': typeof BankTransactionsIndexRoute
  '/counterparties/': typeof CounterpartiesIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bank-transactions/$id/categorize': typeof BankTransactionsIdCategorizeRoute
  '/settings/bank-accounts/$id': typeof SettingsBankAccountsIdRoute
  '/settings/bank-accounts/': typeof SettingsBankAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/activity'
    | '/bank-imports'
    | '/bank-transactions'
    | '/budgets'
    | '/counterparties'
    | '/journal'
    | '/loans'
    | '/login'
    | '/outlook'
    | '/piggy-banks'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/subscriptions'
    | '/accounts/$id'
    | '/counterparties/$id'
    | '/journal/$id'
    | '/journal/new'
    | '/loans/$id'
    | '/settings/bank-accounts'
    | '/settings/currencies'
    | '/settings/preferences'
    | '/settings/tokens'
    | '/settings/users'
    | '/accounts/'
    | '/bank-transactions/'
    | '/counterparties/'
    | '/loans/'
    | '/settings/'
    | '/bank-transactions/$id/categorize'
    | '/settings/bank-accounts/$id'
    | '/settings/bank-accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/bank-imports'
    | '/budgets'
    | '/journal'
    | '/login'
    | '/outlook'
    | '/piggy-banks'
    | '/reports'
    | '/setup'
    | '/subscriptions'
    | '/accounts/$id'
    | '/counterparties/$id'
    | '/journal/$id'
    | '/journal/new'
    | '/loans/$id'
    | '/settings/currencies'
    | '/settings/preferences'
    | '/settings/tokens'
    | '/settings/users'
    | '/accounts'
    | '/bank-transactions'
    | '/counterparties'
    | '/loans'
    | '/settings'
    | '/bank-transactions/$id/categorize'
    | '/settings/bank-accounts/$id'
    | '/settings/bank-accounts'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/activity'
    | '/bank-imports'
    | '/bank-transactions'
    | '/budgets'
    | '/counterparties'
    | '/journal'
    | '/loans'
    | '/login'
    | '/outlook'
    | '/piggy-banks'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/subscriptions'
    | '/accounts/$id'
    | '/counterparties/$id'
    | '/journal/$id'
    | '/journal/new'
    | '/loans/$id'
    | '/settings/bank-accounts'
    | '/settings/currencies'
    | '/settings/preferences'
    | '/settings/tokens'
    | '/settings/users'
    | '/accounts/'
    | '/bank-transactions/'
    | '/counterparties/'
    | '/loans/'
    | '/settings/'
    | '/bank-transactions/$id/categorize'
    | '/settings/bank-accounts/$id'
    | '/settings/bank-accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  BankImportsRoute: typeof BankImportsRoute
  BankTransactionsRoute: typeof BankTransactionsRouteWithChildren
  BudgetsRoute: typeof BudgetsRoute
  CounterpartiesRoute: typeof CounterpartiesRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LoansRoute: typeof LoansRouteWithChildren
  LoginRoute: typeof LoginRoute
  OutlookRoute: typeof OutlookRoute
  PiggyBanksRoute: typeof PiggyBanksRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piggy-banks': {
      id: '/piggy-banks'
      path: '/piggy-banks'
      fullPath: '/piggy-banks'
      preLoaderRoute: typeof PiggyBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook': {
      id: '/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof OutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counterparties': {
      id: '/counterparties'
      path: '/counterparties'
      fullPath: '/counterparties'
      preLoaderRoute: typeof CounterpartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-transactions': {
      id: '/bank-transactions'
      path: '/bank-transactions'
      fullPath: '/bank-transactions'
      preLoaderRoute: typeof BankTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-imports': {
      id: '/bank-imports'
      path: '/bank-imports'
      fullPath: '/bank-imports'
      preLoaderRoute: typeof BankImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/loans/': {
      id: '/loans/'
      path: '/'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof LoansRoute
    }
    '/counterparties/': {
      id: '/counterparties/'
      path: '/'
      fullPath: '/counterparties/'
      preLoaderRoute: typeof CounterpartiesIndexRouteImport
      parentRoute: typeof CounterpartiesRoute
    }
    '/bank-transactions/': {
      id: '/bank-transactions/'
      path: '/'
      fullPath: '/bank-transactions/'
      preLoaderRoute: typeof BankTransactionsIndexRouteImport
      parentRoute: typeof BankTransactionsRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/currencies': {
      id: '/settings/currencies'
      path: '/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof SettingsCurrenciesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/bank-accounts': {
      id: '/settings/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/settings/bank-accounts'
      preLoaderRoute: typeof SettingsBankAccountsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof LoansRoute
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$id': {
      id: '/journal/$id'
      path: '/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof JournalIdRouteImport
      parentRoute: typeof JournalRoute
    }
    '/counterparties/$id': {
      id: '/counterparties/$id'
      path: '/$id'
      fullPath: '/counterparties/$id'
      preLoaderRoute: typeof CounterpartiesIdRouteImport
      parentRoute: typeof CounterpartiesRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/settings/bank-accounts/': {
      id: '/settings/bank-accounts/'
      path: '/'
      fullPath: '/settings/bank-accounts/'
      preLoaderRoute: typeof SettingsBankAccountsIndexRouteImport
      parentRoute: typeof SettingsBankAccountsRoute
    }
    '/settings/bank-accounts/$id': {
      id: '/settings/bank-accounts/$id'
      path: '/$id'
      fullPath: '/settings/bank-accounts/$id'
      preLoaderRoute: typeof SettingsBankAccountsIdRouteImport
      parentRoute: typeof SettingsBankAccountsRoute
    }
    '/bank-transactions/$id/categorize': {
      id: '/bank-transactions/$id/categorize'
      path: '/$id/categorize'
      fullPath: '/bank-transactions/$id/categorize'
      preLoaderRoute: typeof BankTransactionsIdCategorizeRouteImport
      parentRoute: typeof BankTransactionsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface BankTransactionsRouteChildren {
  BankTransactionsIndexRoute: typeof BankTransactionsIndexRoute
  BankTransactionsIdCategorizeRoute: typeof BankTransactionsIdCategorizeRoute
}

const BankTransactionsRouteChildren: BankTransactionsRouteChildren = {
  BankTransactionsIndexRoute: BankTransactionsIndexRoute,
  BankTransactionsIdCategorizeRoute: BankTransactionsIdCategorizeRoute,
}

const BankTransactionsRouteWithChildren =
  BankTransactionsRoute._addFileChildren(BankTransactionsRouteChildren)

interface CounterpartiesRouteChildren {
  CounterpartiesIdRoute: typeof CounterpartiesIdRoute
  CounterpartiesIndexRoute: typeof CounterpartiesIndexRoute
}

const CounterpartiesRouteChildren: CounterpartiesRouteChildren = {
  CounterpartiesIdRoute: CounterpartiesIdRoute,
  CounterpartiesIndexRoute: CounterpartiesIndexRoute,
}

const CounterpartiesRouteWithChildren = CounterpartiesRoute._addFileChildren(
  CounterpartiesRouteChildren,
)

interface JournalRouteChildren {
  JournalIdRoute: typeof JournalIdRoute
  JournalNewRoute: typeof JournalNewRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalIdRoute: JournalIdRoute,
  JournalNewRoute: JournalNewRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface LoansRouteChildren {
  LoansIdRoute: typeof LoansIdRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansIdRoute: LoansIdRoute,
  LoansIndexRoute: LoansIndexRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

interface SettingsBankAccountsRouteChildren {
  SettingsBankAccountsIdRoute: typeof SettingsBankAccountsIdRoute
  SettingsBankAccountsIndexRoute: typeof SettingsBankAccountsIndexRoute
}

const SettingsBankAccountsRouteChildren: SettingsBankAccountsRouteChildren = {
  SettingsBankAccountsIdRoute: SettingsBankAccountsIdRoute,
  SettingsBankAccountsIndexRoute: SettingsBankAccountsIndexRoute,
}

const SettingsBankAccountsRouteWithChildren =
  SettingsBankAccountsRoute._addFileChildren(SettingsBankAccountsRouteChildren)

interface SettingsRouteChildren {
  SettingsBankAccountsRoute: typeof SettingsBankAccountsRouteWithChildren
  SettingsCurrenciesRoute: typeof SettingsCurrenciesRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsTokensRoute: typeof SettingsTokensRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBankAccountsRoute: SettingsBankAccountsRouteWithChildren,
  SettingsCurrenciesRoute: SettingsCurrenciesRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsTokensRoute: SettingsTokensRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  ActivityRoute: ActivityRoute,
  BankImportsRoute: BankImportsRoute,
  BankTransactionsRoute: BankTransactionsRouteWithChildren,
  BudgetsRoute: BudgetsRoute,
  CounterpartiesRoute: CounterpartiesRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LoansRoute: LoansRouteWithChildren,
  LoginRoute: LoginRoute,
  OutlookRoute: OutlookRoute,
  PiggyBanksRoute: PiggyBanksRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
